name: working_hours_app-brave_ishizaka
services:
  app:
    command:
    - infinity
    entrypoint:
    - sleep
    image: docker/dev-environments-default:stable-1
    init: true
    labels:
      com.docker.devenvironments: "true"
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.container: "true"
      com.docker.devenvironments.name: working_hours_app-brave_ishizaka
    networks:
      default: null
    stop_signal: SIGKILL
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    - type: volume
      source: volume-working_hours_app-brave_ishizaka
      target: /com.docker.devenvironments.code
    - type: volume
      source: vsCodeServerVolume-working_hours_app-brave_ishizaka-app
      target: /home/vscode
networks:
  default:
    name: working_hours_app-brave_ishizaka_default
volumes:
  volume-working_hours_app-brave_ishizaka:
    name: volume-working_hours_app-brave_ishizaka
    external: true
  vsCodeServerVolume-working_hours_app-brave_ishizaka-app:
    name: vsCodeServerVolume-working_hours_app-brave_ishizaka-app
