version: '3.2.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    image: myapp
    build: .
    ports:
      - 3000:3000
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword

